### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by tadvi** [fharding1/gemux#2]
Documentation missing on how to serve static files using http.FileServer(http.Dir(*dir)).
Because typical setup:

mux.Get("/static/", http.StripPrefix("/static/", http.FileServer(http.Dir("static"))))

Does not work.

**Comment by fharding1** [comment]
Hi tavdi, this library matches strictly on paths. There's no matching on prefixes, meaning if you want to serve static files using this library you need to register a route for each file.
